FROM alpine:3.14.0

WORKDIR /app

RUN chown nobody /app

COPY --chown=nobody:root bin/run run
COPY --chown=nobody:root src/target/x86_64-unknown-linux-musl/release/emojied emojied
COPY --chown=nobody:root public public

EXPOSE 3000

CMD ["/app/run"]
