name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Build release and deploy
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/main' }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup local database
        run: |
          createdb emojied_db && \
          nix develop .#devShells.x86_64-linux.ci \
            --command sqitch deploy

      - name: Build server
        run: |
          docker run \
            --network=host \
            --rm -it \
            -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder \
            cargo build --release
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/emojied_db

      - name: Send off to Fly.io
        uses: superfly/flyctl-actions@1.3
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy --local-only"
