name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Build release and deploy
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/main' }}
    container: ubuntu:focal

    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Db dependencies
        run: |
          apt update -y && \
          apt install sqitch libdbd-pg-perl postgresql-client -y

      - name: Migrate local database
        run: |
          sqitch \
            --db-host localhost \
            --db-name postgres \
            --db-user postgres \
            --db-port 5432 \
            deploy
        env:
          SQITCH_PASSWORD: postgres

      - name: Build server
        run: |
          docker run \
            --network=host \
            --rm -it \
            -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder \
            cargo build --release
        env:
          DATABASE_URL: postgres://postgres@localhost/emojied_db

      # - name: Send off to Fly.io
      #   uses: superfly/flyctl-actions@1.3
      #   env:
      #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      #   with:
      #     args: "deploy --local-only"

      # - name: Run migrations
      #   run: |
      #     nix develop .#devShells.x86_64-linux.ci \
      #       --command sqitch deploy
