name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build release and deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Nix
        uses: cachix/install-nix-action@v15

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build image
        run: |
          nix build .#emojied-docker
          docker load < result

      - name: Rename image
        run: docker tag emojied-docker:latest hsekun/emojied:latest

      - name: Push image
        run: docker push hsekun/emojied:latest
