name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build release and deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Nix
        uses: cachix/install-nix-action@v15

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Check contents
        run: |
          ls -la
          ls -la public/

      - name: Test emojied
        run: |
          nix develop .#devShells.x86_64-linux.ci \
            --command cargo test

      - name: Process stylesheet
        run: |
          nix develop .#devShells.x86_64-linux.ci --command \
            tailwindcss \
              --input assets/app.css \
              --config assets/tailwind.config.js \
              --output public/app.css \
              --minify

      - name: Process TS source file
        run: |
          nix develop .#devShells.x86_64-linux.ci --command \
            esbuild \
              assets/app.ts \
              --outdir=public/ \
              --minify

      - name: Build static binary
        run: |
          docker run \
            -v ~/.cargo/git:/home/rust/.cargo/git \
            -v ~/.cargo/registry:/home/rust/.cargo/registry \
            -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder /bin/sh \
            -c "sudo chown -R rust:rust /home/rust/.cargo/git /home/rust/.cargo/registry /home/rust/src/target && cargo build --release"

      - name: Check contents
        run: |
          ls -la
          ls -la target/
          ls -la public/

      - name: Build image
        run: |
          docker build . --file Dockerfile.ci --tag hsekun/emojied:latest

      - name: Push image
        run: docker push hsekun/emojied:latest

      - name: Generate release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            public/
            target/x86_64-unknown-linux-musl/release/emojied
